import { StyleSheet } from 'react-native';

export const resets = StyleSheet.create({
    line2: {
      position: 'relative',
      left: 36.8222,
      top: 50,
      width: 17.0062,
      maxWidth: '100%',
      height: 17.0062,
      maxHeight: '100%',
    },
    line2Before: {
      alignContent: 'center',
      position: 'absolute',
      top: 0,
      left: 0,
      transformOrigin: '0 0',
      transform: 'translateX(17.0062px) rotate(135deg)',
      width: 20.0504,
      height: 0,
      borderWidth: 2,
      borderColor: '#000',
      borderStyle: 'solid',
    },
    line3: {
      position: 'relative',
      left: 22,
      top: 64.8222,
      width: 17.0062,
      maxWidth: '100%',
      height: 17.0062,
      maxHeight: '100%',
    },
    line3Before: {
      alignContent: 'center',
      position: 'absolute',
      top: 0,
      left: 0,
      transformOrigin: '0 0',
      transform: 'rotate(45deg)',
      width: 20.0504,
      height: 0,
      borderWidth: 2,
      borderColor: '#000',
      borderStyle: 'solid',
    },
    rectangle49: {
      position: 'absolute',
      left: 11,
      bottom: 414,
      width: 370,
      height: 59,
      borderRadius: 10,
      backgroundColor: '#56c4d2',
    },
    aLTERAR: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
      fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
      position: 'absolute',
      justifyContent: 'center',
      //left: `${(Dimensions.get('window').width / 2) + 0.782}px`,
  
      bottom: 431,
      width: 69.564,
      minHeight: 100,
      textAlign: 'center',
      alignItems: 'center',
      flexDirection: 'column',
      transform: [{ translateX: -50 }],
    },
    rectangle492: {
        position: 'absolute',
        left: 11,
        bottom: 336,
        width: 370,
        height: 59,
        borderRadius: 10,
        backgroundColor: '#e03131',
      },
      dELATAR: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        position: 'absolute',
        //left: 'calc(50% - -1px)',
        //top: 'calc(50% - -165.5px)',
        justifyContent: 'center',
        width: 126,
        minHeight: 100,
        textAlign: 'center',
        alignItems: 'center',
        flexDirection: 'column',
        transform: [{translateX: -50}],
      },
      rectangle47: {
        margin: "auto",
        top: -190,
        width: 162,
        height: 238,
        borderRadius: 30,
        //backgroundImage: `url('/assets/rectangle47.jpeg')`, // Replace with actual image path
        //backgroundPosition: 'center',
        //backgroundRepeat: 'no-repeat',
        //backgroundSize: 'cover',
      },
      tereLiye: {
        color: '#000',
        fontSize: 16,
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        position: 'absolute',
        left: 162,
        top: 426,
        minWidth: 100,
        minHeight: 100,
        textAlign: 'center',
        alignItems: 'center',
        //whiteSpace: 'nowrap',
        flexDirection: 'column',
      },
      AUTOR: {
        color: '#000',
        fontSize: 16,
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        position: 'absolute',
        left: 162,
        top: 455,
        minWidth: 100,
        minHeight: 100,
        textAlign: 'center',
        alignItems: 'center',
        //whiteSpace: 'nowrap',
        flexDirection: 'column',
      },
      sITUACAO: {
        color: '#000',
        fontSize: 16,
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        position: 'absolute',
        left:   
     197,
        top: 467,
        minWidth: 100,
        minHeight: 100,
        textAlign: 'center',
        alignItems: 'center',
        //whiteSpace: 'nowrap',
        flexDirection: 'column',
      },
      bintang: {
        color: '#000',
        fontSize: 24,
        fontWeight: '600',
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        position: 'absolute',
        left: 143,
        top: 390,
        minWidth: 100,
        minHeight: 100,
        textAlign: 'center',
        alignItems: 'center',
        //whiteSpace: 'nowrap',
        flexDirection: 'column',
      },
      line4: {
        position: 'absolute',
        left: 9,
        top: 558,
        width: 371,
        maxWidth: '100%',
        height: 0,
        maxHeight: '100%',
        borderBottomWidth: 1,
        borderBottomColor: '#d9d9d9',
        borderStyle: 'solid',
      },
      rectangle48: {
        position: 'absolute',
        left: 145,
        top: 355,
        width: 131,
        height: 29,
        borderRadius: 6,
        backgroundColor: '#56c4d2',
      },
      romance: {
        //color: '#e0f4f6',
        color: "white",
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Poppins, system-ui, -apple-system',
        position: 'absolute',
        left: -10,
        top: 5,
        minWidth: 150,
        minHeight: 100,
        textAlign: 'center',
        alignItems: 'center',
        //whiteSpace: 'nowrap',
        //flexDirection: 'column',
      },
      _102: {
        color: '#000',
        fontSize: 24,
        fontWeight: '600',
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        position: 'absolute',
        left:   
     171,
        top: 523,
        width: 72,
        minHeight: 100,
        flexDirection: 'column',
      },
      pAGES: {
        color: '#000',
        fontSize: 14,
        fontWeight: '300',
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        position: 'absolute',
        left:   
     171,
        top: 503,
        width: 47,
        minHeight: 100,
        flexDirection: 'column',
      },
      rectangle10: {
        position: 'absolute',
        left: '50%',
        top: 0,
        width: 390,
        height: 42.8271,
        backgroundColor: '#fff',
        transform: [{translateX: -50}],
      },
      rectangle5: {
        position: 'absolute',
        //left: 'calc(50% - -100.8224px)',
        justifyContent: 'center',
        top: 24.6028,
        width: 3.6449,
        height: 5.4673,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{translateX: -50}],
      },
      rectangle6: {
        position: 'absolute',
        //left: 'calc(50% - -105.3785px)',
        justifyContent: 'center',
        top: 22.7804,
        width: 3.6449,
        height: 7.2897,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{translateX: -50}],
      },
      rectangle7: {
        position: 'absolute',
        //left: 'calc(50% - -109.9346px)',
        justifyContent: 'center',
        top: 20.9579,
        width: 3.6449,
        height: 9.1121,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{translateX: -50}],
      },
      rectangle8: {
        position: 'absolute',
        //left: 'calc(50% - -114.4906px)',
        justifyContent: 'center',
        top: 18.2243,
        width: 3.6449,
        height: 11.8458,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{translateX: -50}],
      },
      _835: {
        color: '#000',
        fontSize: 14,
        fontWeight: '600',
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        position: 'absolute',
        //left: 'calc(50% - 157.5px)',
        justifyContent: 'center',
        top: 12,
        width: 41,
        height: 19,
        textAlign: 'center',
        alignItems: 'center',
        flexDirection: 'column',
        transform: [{translateX: -50}],
      },
      _4G: {
        color: '#000',
        fontSize: 14,
        fontWeight: '600',
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        position: 'absolute',
        //left: 'calc(50% - -132.5px)',
        justifyContent: 'center',
        top: 15,
        width: 27,
        height: 19,
        textAlign: 'center',
        alignItems: 'center',
        flexDirection: 'column',
        transform: [{translateX: -50}],
      },
      rectangle9: {
        position: 'absolute',
        //left: 'calc(50% - -162.1962px)',
        justifyContent: 'center',
        top: 18.2243,
        width: 25.514,
        height: 11.8458,
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: '#d9d9d9',
        borderEndWidth: 1,
        borderRadius: 3,
        backgroundColor: '#000',
        transform: [{translateX: -50}],
      },
  });