import { StyleSheet } from 'react-native';

export const stylesEmprestar = StyleSheet.create({
    dockedInputDatePickerDesktop: {
      //left: 38,
      //top: 546,
      transform: [{translateY: -271}, {translateX: 70}],
      height: 68,
    },
    textField: {
      position: 'absolute',
    },
    inputText: {
      color: '#1d1b20',
      fontSize: 16,
      lineHeight: 24,
      fontFamily: 'Roboto, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
      letterSpacing: 0.5,
      //width: 'min-content',
      //height: 'min-content',
      //whiteSpace: 'nowrap',
      flexDirection: 'column',
    },
    dockedInputDatePickerDesktop2: {
      //left: 38,
      //top: 663,
      transform: [{translateY: -257}, {translateX: 70}],
      height: 68,
    },
    textField2: {
      position: 'absolute',
    },
    inputText2: {
      color: '#1d1b20',
      fontSize: 16,
      lineHeight: 24,
      fontFamily: 'Roboto, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
      letterSpacing: 0.5,
      //width: 'min-content',
      //height: 'min-content',
      //whiteSpace: 'nowrap',
      flexDirection: 'column',
    },
    root: {
      //position: 'relative',
      flex: 1,
      alignSelf: 'stretch',
      flexDirection: 'column',
      alignItems: 'flex-start',
      backgroundColor: '#DAE9C8',
      height: 900,
      width: 420,
      //overflowY: 'auto',
      //overflowX: 'hidden',
    },
    rectangle24: {
        position: 'absolute',
      transform: [{translateY: 600}, {translateX: 38}],
      width: 342,
      height: 63,
      borderRadius: 20,
      backgroundColor: '#90a67f',
    },
    eMPRESTAR: {
      color: '#fff',
      fontSize: 24,
      fontWeight: '900',
      fontFamily: 'Times New Roman',
      margin: 'auto',
      //width: 'min-content',
      //height: 'min-content',
      textAlign: 'center',
      alignItems: 'center',
      //whiteSpace: 'nowrap',
      flexDirection: 'column',
    },
    eMPRESTARLIVRO: {
      color: '#000',
      fontSize: 24,
      fontFamily: 'Times New Roman',
      margin: 'auto',
      //position: 'absolute',
      //left: 84,
      transform: [{translateY: -180}],
      //width: 'min-content',
      //height: 'min-content',
      textAlign: 'center',
      alignItems: 'center',
      //whiteSpace: 'nowrap',
      flexDirection: 'column',
    },
    tITULO: {
      color: '#000',
      fontSize: 24,
      fontFamily: 'Times New Roman',
      fontWeight: '900',
      //position: 'absolute',
      //left: 149,
      //top: 348,
      transform: [{translateY: -150}],
      marginLeft: 'auto',
      marginRight: 'auto',
      //width: 'min-content',
      //height: 'min-content',
      textAlign: 'center',
      alignItems: 'center',
      //whiteSpace: 'nowrap',
      flexDirection: 'column',
    },
    aUTOR: {
        color: '#000',
        fontSize: 14,
        fontFamily: 'Times New Roman',
        fontWeight: '900',
        transform: [{translateY: -135}],
        marginLeft: 'auto',
        marginRight: 'auto',
        //width: 'min-content',
        //height: 'min-content',
        textAlign: 'center',
        alignItems: 'center',
        //whiteSpace: 'nowrap',
        flexDirection: 'column',
      },
      nOME: {
        color: '#000',
        fontSize: 14,
        fontFamily: 'Times New Roman',
        fontWeight: '900',
        transform: [{translateY: -110}, {translateX: 60}],
        //width: 'min-content',
        //height: 'min-content',
        textAlign: 'center',
        alignItems: 'center',
        //whiteSpace: 'nowrap',
        flexDirection: 'column',
      },
      fotoPagina: {
        //position: 'absolute',
        //left: 122,
        //top: 105,
        transform: [{translateY: -420}, {translateX: 140}],
        width: 146,
        height: 219,
        borderRadius: 30,
        //backgroundImage: `url('/assets/fotoPagina.jpeg')`, // Replace with actual image path
        //backgroundPosition: 'center',
        //backgroundRepeat: 'no-repeat',
        //backgroundSize: 'cover',
      },
      dATADEEMPRESTIMO: {
        color: '#000',
        fontSize: 17,
        fontFamily: 'Times New Roman',
        transform: [{translateY: -230}, {translateX: 200}],
        //width: 'min-content',
        //height: 'min-content',
        textAlign: 'center',
        alignItems: 'center',
        //whiteSpace: 'nowrap',
        flexDirection: 'column',
      },
      dATADEDEVOLUCAO: {
        color: '#000',
        fontSize: 17,
        fontFamily: 'Times New Roman',
        transform: [{translateY: -300}, {translateX: 200}],
        //width: 'min-content',
        //height: 'min-content',
        textAlign: 'center',
        alignItems: 'center',
        //whiteSpace: 'nowrap',
        flexDirection: 'column',
      },
      rectangle242: {
        transform: [{translateY: -490}],
        marginLeft: 'auto',
        marginRight: 'auto',
        width: 320,
        height: 53,
        borderWidth: 2,
        borderColor: '#00000026',
        borderStyle: 'solid',
        borderRadius: 20,
        backgroundColor: '#f7f7f7',
      },
      rectangle10: {
        position: 'absolute',
        left: '50%',
        top: 0,
        width: 390,
        height: 42.8271,
        backgroundColor: '#fff',
        transform: [{translateX: 50}],
      },
      rectangle5: {
        position: 'absolute',
        //left: 'calc(50% - -100.8224px)',
        top: 24.6028,
        width: 3.6449,
        height: 5.4673,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{translateX: 50}],

      },
      rectangle6: {
        position: 'absolute',
        //left: 'calc(50% - -105.3785px)',
        top: 22.7804,
        width: 3.6449,
        height: 7.2897,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{translateX: 50}],

      },
      rectangle7: {
        position: 'absolute',
        //left: 'calc(50% - -109.9346px)',
        top: 20.9579,
        width: 3.6449,
        height: 9.1121,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{translateX: 50}],

      },
      rectangle8: {
        position: 'absolute',
        //left: 'calc(50% - -114.4906px)',
        top: 18.2243,
        width: 3.6449,
        height: 11.8458,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{translateX: 50}],

      },
      _835: {
        color: '#000',
        fontSize: 14,
        fontWeight: '600',
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        position: 'absolute',
        //left: 'calc(50% - 157.5px)',   
    
        top: 12,
        width: 41,
        height: 19,
        textAlign: 'center',
        alignItems: 'center',
        flexDirection: 'column',
        transform: [{translateX: 50}],

      },
      _4G: {
        color: '#000',
        fontSize: 14,
        fontWeight: '600',
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        position: 'absolute',
        //left: 'calc(50% - -132.5px)',   
    
        top: 15,
        width: 27,
        height: 19,
        textAlign: 'center',
        alignItems: 'center',
        flexDirection: 'column',
        transform: [{translateX: 50}],

      },
      rectangle9: {
        position: 'absolute',
        //left: 'calc(50% - -162.1962px)',
        top: 18.2243,
        width: 25.514,
        height: 11.8458,
        borderWidth: 1,
        borderColor: '#d9d9d9',
        borderStyle: 'solid',
        //borderOffset: -1,
        borderRadius: 3,
        backgroundColor: '#000',
        transform: [{translateX: 50}],

      },
  });