import { StyleSheet } from 'react-native';

export const styleEmpres = StyleSheet.create({
    retanguloToFlatList: {
      //position: 'static',
      margin: 'auto',
      top: 10,
      width: 400,
      height: 50
    },
    group95: {
      transform: [{translateX: 60}, {translateY: 110}],
      width: 300,
      height: 40, 
      borderWidth: 1, 
      borderColor: "#999", 
      borderRadius: 9
    },
    bookOpen: {
      left: 178,
      top: 143,
      width: 29,
      height: 28,
    },
    icon: {
      width: '100%',
      height: '100%',
    },
    root: {
      //position: 'absolute',
      flex: 1,
      //alignSelf: 'stretch',
      flexDirection: 'column',
      alignItems: 'flex-start',
      backgroundColor: '#f3ffe0',
      //overflow: 'scroll'
    },
    rectangle15: {
      //position: 'absolute',
      left: 0,
      top: 0,
      width: 390,
      height: 832,
      backgroundColor: '#fafafa',
    },
    rectangle16: {
      //position: 'absolute',
      left: 0,
      top: 0,
      width: 390,
      height: 832,
      backgroundColor: '#fff',
    },
    hasilScan: {
      color: '#000',
      fontSize: 24,
      fontWeight: '600',
      fontFamily: 'Times New Roman \ Arial',
      //position: 'absolute',
      transform: [{translateY: 80}, {translateX: 84}],
      //minWidth: 'auto',
      //minHeight: 'auto',
      //flexDirection: 'column',
    },
    line10: {
      left: 17,
      top: 186,
      width: 133,
      maxWidth: '100%',
      height: 0,
      maxHeight: '100%',
      borderWidth: 1.5,
      borderColor: '#1c578f',
      borderStyle: 'solid',
    },
    rectangle50: {
      position: 'absolute',
      left: 15,
      //top: 200,
      //transform: [{translateY: 120}],
      width: 380.9941,
      height: 127.503,
      borderRadius: 11,
      backgroundColor: '#fff',
    },
    rectangle51: {
      //position: 'absolute',
      left: 24.8521,
      //top: 200.8529,
      //transform: [{translateY: 123}],
      width: 83.9822,
      height: 120.8876,
      marginBottom: -67,
      borderRadius: 11,
      backgroundColor: 'black'
    },
    tITULO: {
      color: '#000',
      fontSize: 20,
      fontWeight: '600',
      fontFamily: 'Times New Roman \ Arial',
      //position: 'absolute',
      left: 133,
      //top: 155,
      width: 258,
      transform: [{translateY: -40}],
      //height: 35,
      flexDirection: 'column',
    },
    pESSOA: {
        color: '#000',
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Times New Roman \ Arial',
        //position: 'absolute',
        left: 133,
        //top: 155,
        width: 258,
        transform: [{translateY: -35}],
        //height: 35,
        flexDirection: 'column',
      },
    eMPRESTIMO: {
      color: '#000',
      fontSize: 15,
      fontWeight: 'bold',
      fontFamily: 'Times New Roman \ Arial',
      //position: 'absolute',
      //left: 133,
      //top: 160,
      //transform: [{translateY: -25}],
      margin: 'auto',
      //height: 17,
      //flexDirection: 'column',
    },
    dEVOLUCAO: {
        color: '#000',
        fontSize: 15,
        fontWeight: 'bold',
        fontFamily: 'Times New Roman \ Arial',
        //position: 'absolute',
        //left: 133,
        //top: 196,
        //transform: [{translateY: 0}],
        margin: 'auto'
        //height: 17,
        //flexDirection: 'column',
      },
      pAGINAS: {
        color: '#000',
        fontSize: 12,
        fontWeight: '500',
        fontFamily: 'Times New Roman \ Arial',
        //position: 'absolute',
        left: 133,
        //top: 200,
        transform: [{translateY: -5}],
        width: 101,
        //height: 18,
        flexDirection: 'column',
      },
      line5: {
        //position: 'absolute',
        left: 31.497,
        //top: 375.7,
        width: 329.9408,
        maxWidth: "100%",
        maxHeight: "100%",
        transform: [{translateY: 40}],
        borderBottomWidth: 0.3,
        borderBottomColor: '#0000004d',
        borderStyle: 'solid',
      },
      rectangle136: {
        //position: 'absolute',
        left: 130,
        width: 180,
        height: 20,
        marginBottom: -40,
        borderRadius: 12,
        transform: [{translateY: -30}],
        backgroundColor: '#90a67f',
      },
      rectangle137: {
        left: 130,
        width: 180,
        height: 20,
        borderRadius: 12,
        transform: [{translateY: 20}],
        backgroundColor: '#90a67f',
      },
      diaDePrazo: {
        left: 130,
        width: 180,
        height: 20,
        borderRadius: 12,
        transform: [{translateY: 20}],
        backgroundColor: 'red',
      },
      vER: {
        //color: '#fff',
        color: 'black',
        //fontWeight: '600',
        //fontFamily: 'Times New Roman',
        //position: 'absolute',
        //left: 300,
        //width: 380,
        //height: 30,
        margin: 'auto',
        //textAlign: 'center',
        //alignItems: 'center',
        //flexDirection: 'column',
      },
      rectangle10: {
        //position: 'absolute',
        left: '50%',
        top: 0,
        width: 390,
        height: 42.8271,
        backgroundColor: '#fff',
        transform: [{ translateX: -50 }],
      },
      rectangle5: {
        //position: 'absolute',
        left: 'auto',
        top: 200.6028,
        width: 3.6449,
        height: 5.4673,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{ translateX: -50 }],
      },
      rectangle6: {
        //position: 'absolute',
        left: 'auto',
        top: 22.7804,
        width: 3.6449,
        height: 7.2897,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{ translateX: -50 }],
      },
      rectangle7: {
        //position: 'absolute',
        left: 'auto',
        top: 20.9579,
        width: 3.6449,
        height: 9.1121,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{ translateX: -50 }],
      },
      rectangle8: {
        //position: 'absolute',
        left: 'auto',
        top: 1.2243,
        width: 3.6449,
        height: 11.8458,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{ translateX: -50 }],
      },
      _835: {
        color: '#000',
        fontSize: 14,
        fontWeight: '600',
        fontFamily: 'Times New Roman \ Arial',
        //position: 'absolute',
        left: 'auto',
        top: 12,
        width: 41,
        height: 19,
        textAlign: 'center',
        alignItems: 'center',
        flexDirection: 'column',
        transform: [{ translateX: -50 }],
      },
      _4G: {
        color: '#000',
        fontSize: 14,
        fontWeight: '600',
        fontFamily: 'Times New Roman \ Arial',
        position: 'absolute',
        left: 'auto',
        top: 15,
        width: 27,
        height: 19,
        textAlign: 'center',
        alignItems: 'center',
        flexDirection: 'column',
        transform: [{ translateX: -50 }],
      },
      rectangle9: {
        //position: 'absolute',
        left: 'auto',
        top: 18.2243,
        width: 25.514,
        height: 11.8458,
        borderWidth: 1,
        borderColor: '#d9d9d9',
        borderStyle: 'solid',
        //borderOffset: -1,
        borderRadius: 3,
        backgroundColor: '#000',
        transform: [{ translateX: -50 }],
      },
  });