import { StyleSheet } from 'react-native';

export const stylesRegister = StyleSheet.create({
    root: {
      //position: 'relative',
      flex: 1,
      alignSelf: 'stretch',
      flexDirection: 'column',
      alignItems: 'flex-start',
      backgroundColor: '#fff',
      width: 415,
      transform: [{translateY: 0}],
      height: 1100
      //overflowY: 'auto',
      //overflowX: 'hidden',
    },
    rectangle24: {
      //position: 'absolute',
      left: 24,
      transform: [{translateY: 300}, {translateX: 14}],
      width: 342,
      height: 63,
      borderWidth: 2,
      color: 'black',
      borderColor: '#00000026',
      borderStyle: 'solid',
      borderRadius: 20,
      backgroundColor: '#f7f7f7',
    },
    chooseImage:{
        transform: [{translateY: 238}, {translateX: 285}],
    },
    tITULO: {
      color: '#00000080',
      fontSize: 16,
      fontWeight: '600',
      fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
      position: 'absolute',
      left: 50,
      top: 358,
      //width: 'min-content',
      //height: 'min-content',
      //whiteSpace: 'nowrap',
      flexDirection: 'column',
    },
    rectangle242: {
      //position: 'absolute',
      left: 24,
      transform: [{translateY: 310}, {translateX: 14}],
      width: 342,
      height: 63,
      borderWidth: 2,
      borderColor: '#00000026',
      borderStyle: 'solid',
      borderRadius: 20,
      backgroundColor: '#f7f7f7',
    },
    aUTOR: {
      color: '#00000080',
      fontSize: 16,
      fontWeight: '600',
      fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
      //position: 'absolute',
      transform: [{translateY: 430}, {translateX: 120}],
      //width: 'min-content',
      //height: 'min-content',
      //whiteSpace: 'nowrap',
      flexDirection: 'column',
    },
    rectangle243: {
      //position: 'absolute',
      left: 24,
      transform: [{translateY: 305}, {translateX: 14}],
      width: 342,
      height: 63,
      borderWidth: 2,
      borderColor: '#00000026',
      borderStyle: 'solid',
      borderRadius: 20,
      backgroundColor: '#f7f7f7',
    },
    eSTADO: {
      color: '#00000080',
      fontSize: 16,
      fontWeight: '600',
      fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
      position: 'absolute',
      left: 50,
      top: 497,
      //width: 'min-content',
      //height: 'min-content',
      //whiteSpace: 'nowrap',
      flexDirection: 'column',
    },
    rectangle244: {
      //position: 'absolute',
      left: 24,
      transform: [{translateY: 315}, {translateX: 14}],
      width: 342,
      height: 63,
      borderWidth: 2,
      borderColor: '#00000026',
      borderStyle: 'solid',
      borderRadius: 20,
      backgroundColor: '#f7f7f7',
    },
    gENERO: {
      color: '#00000080',
      fontSize: 16,
      fontWeight: '600',
      fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
      position: 'absolute',
      left: 50,
      top: 567,
      //width: 'min-content',
      //height: 'min-content',
      //whiteSpace: 'nowrap',
      flexDirection: 'column',
    },
    rectangle245: {
      //position: 'absolute',
      left: 24,
      transform: [{translateY: 325}, {translateX: 14}],
      width: 342,
      height: 63,
      borderWidth: 2,
      borderColor: '#00000026',
      borderStyle: 'solid',
      borderRadius: 20,
      backgroundColor: '#f7f7f7',
    },
    pAGINAS: {
      color: '#00000080',
      fontSize: 16,
      fontWeight: '600',
      fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
      position: 'absolute',
      left: 50,
      top: 637,
      //width: 'min-content',
      //height: 'min-content',
      //whiteSpace: 'nowrap',
      flexDirection: 'column',
    },
    rectangle246: {
        //position: 'absolute',
        left: 24,
        transform: [{translateY: 335}, {translateX: 14}],
        width: 342,
        height: 63,
        borderWidth: 2,
        borderColor: '#00000026',
        borderStyle: 'solid',
        borderRadius: 20,
        backgroundColor: '#f7f7f7',
      },
      iDOMA: {
        color: '#00000080',
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        position: 'absolute',
        left: 50,
        top: 707,
        //width: 'min-content',
        //height: 'min-content',
        //whiteSpace: 'nowrap',
        flexDirection: 'column',
      },
      rectangle247: {
        //position: 'absolute',
        width: 342,
        height: 63,
        borderRadius: 20,
        backgroundColor: '#90a67f',
        transform: [{translateY: 355}, {translateX: 39}],
      },
      sALVAR: {
        color: '#fff',
        fontWeight: '600',
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        margin: 'auto',
        //position: 'absolute',
        //width: 'min-content',
        //height: 'min-content',
        textAlign: 'center',
        alignItems: 'center',
        //whiteSpace: 'nowrap',
        flexDirection: 'column',
      },
      _2024: {
        //position: 'absolute',
        bottom: -300,
        margin: 'auto',
        width: 52,
        height: 95,
        textAlign: 'center',
        alignItems: 'center',
        flexDirection: 'column',
      },
      textBlock: {
        color: '#0f0f0f',
        fontSize: 16,
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
      },
      textBlock2: {
        marginTop:   
     0,
        color: '#0f0f0f',
        fontSize: 16,
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
      },
      textBlock3: {
        marginTop:   
     0,
        color: '#0f0f0f',
        fontSize: 16,
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
      },
      textBlock4: {
        marginTop:   
     0,
        color: '#0f0f0f',
        fontSize: 16,
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
      },
      cADASTRARLIVRO: {
        color: '#000',
        fontSize: 24,
        fontWeight: '600',
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        transform: [{translateY: 70}, {translateX: 115}],
        //position: 'absolute',
        //width: 'min-content',
        //height: 'min-content',
        textAlign: 'center',
        alignItems: 'center',
        //whiteSpace: 'nowrap',
        flexDirection: 'column',
      },
      fotoPagina: {
        //position: 'absolute',
        width: 146,
        height: 219,
        borderRadius: 30,
        backgroundColor: 'purple',
        transform: [{translateY: 130}, {translateX: 135}],
        marginBottom: -130
        //backgroundImage: `url('/assets/fotoPagina.jpeg')`, // Replace with actual image path
        //backgroundPosition: 'center',
        //backgroundRepeat: 'no-repeat',
        //backgroundSize: 'cover',
      },
      rectangle10: {
        position: 'absolute',
        left: '50%',
        top: 0,
        width: 390,
        height: 42.8271,
        backgroundColor: '#fff',
        transform: [{translateX: 50}],
      },
      rectangle5: {
        position: 'absolute',
        //left: 'calc(50% - -100.8224px)',
        top: 24.6028,
        width: 3.6449,
        height: 5.4673,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{translateX: 50}],
      },
      rectangle6: {
        position: 'absolute',
        //left: 'calc(50% - -105.3785px)',
        top: 22.7804,
        width: 3.6449,
        height: 7.2897,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{translateX: 50}],
      },
      rectangle7: {
        position: 'absolute',
        //left: 'calc(50% - -109.9346px)',
        top: 20.9579,
        width: 3.6449,
        height: 9.1121,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{translateX: 50}],
      },
      rectangle8: {
        position: 'absolute',
        //left: 'calc(50% - -114.4906px)',
        top: 18.2243,
        width: 3.6449,
        height: 11.8458,
        borderRadius: 15,
        backgroundColor: '#000',
        transform: [{translateX: 50}],
      },
      _835: {
        color: '#000',
        fontSize: 14,
        fontWeight: '600',
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        position: 'absolute',
        //left: 'calc(50% - 157.5px)',   
        top: 12,
        width: 41,
        height: 19,
        textAlign: 'center',
        alignItems: 'center',
        flexDirection: 'column',
        transform: [{translateX: 50}],
      },
      _4G: {
        color: '#000',
        fontSize: 14,
        fontWeight: '600',
        fontFamily: 'Poppins, system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, \'Noto Sans\', \'Liberation Sans\', sans-serif',
        position: 'absolute',
        //left: 'calc(50% - -132.5px)',
        top: 15,
        width: 27,
        height: 19,
        textAlign: 'center',
        alignItems: 'center',
        flexDirection: 'column',
        transform: [{translateX: 50}],
      },
      rectangle9: {
        position: 'absolute',
        //left: 'calc(50% - -162.1962px)',
        top: 18.2243,
        width: 25.514,
        height: 11.8458,
        borderWidth: 1,
        borderColor: '#d9d9d9',
        borderStyle: 'solid',
        //borderOffset: -1,
        borderRadius: 3,
        backgroundColor: '#000',
        transform: [{translateX: 50}],
      },
  });